import { createCipheriv, createDecipheriv, createHmac, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";

export function sha256(value, pepper="") { return createHmac("sha256",pepper).update(String(value)).digest("hex"); }
export function makePasswordRecord(password){const salt=randomBytes(16).toString("hex");return{salt,digest:scryptSync(password,salt,64).toString("hex")};}
export function verifyPassword(password,record){if(!record?.salt||!record?.digest)return false;const a=scryptSync(password,record.salt,64),b=Buffer.from(record.digest,"hex");return a.length===b.length&&timingSafeEqual(a,b);}
export function strongPassword(password){return typeof password==="string"&&password.length>=12&&password.length<=200&&/[a-z]/.test(password)&&/[A-Z]/.test(password)&&/[0-9]/.test(password)&&/[^A-Za-z0-9]/.test(password);}
export function encryptSecret(value,keyBase64){const key=Buffer.from(keyBase64,"base64");if(key.length!==32)throw new Error("MFA encryption key must be 32 bytes.");const iv=randomBytes(12),cipher=createCipheriv("aes-256-gcm",key,iv);const encrypted=Buffer.concat([cipher.update(value,"utf8"),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString("base64");}
export function decryptSecret(value,keyBase64){const key=Buffer.from(keyBase64,"base64"),raw=Buffer.from(value,"base64"),iv=raw.subarray(0,12),tag=raw.subarray(12,28),data=raw.subarray(28),decipher=createDecipheriv("aes-256-gcm",key,iv);decipher.setAuthTag(tag);return Buffer.concat([decipher.update(data),decipher.final()]).toString("utf8");}
function decodeBase32(input){const alphabet="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits="",out=[];for(const char of input.replace(/=+$/g,"").toUpperCase()){const n=alphabet.indexOf(char);if(n<0)throw new Error("Invalid base32 secret.");bits+=n.toString(2).padStart(5,"0");}for(let i=0;i+8<=bits.length;i+=8)out.push(parseInt(bits.slice(i,i+8),2));return Buffer.from(out);}
export function totp(secret,time=Date.now(),step=30){const counter=Math.floor(time/1000/step),buffer=Buffer.alloc(8);buffer.writeBigUInt64BE(BigInt(counter));const digest=createHmac("sha1",decodeBase32(secret)).update(buffer).digest(),offset=digest[digest.length-1]&15,code=(digest.readUInt32BE(offset)&0x7fffffff)%1_000_000;return String(code).padStart(6,"0");}
export function verifyTotp(secret,code,time=Date.now()){if(!/^\d{6}$/.test(String(code)))return false;return[-1,0,1].some(window=>{const expected=totp(secret,time+window*30_000);return timingSafeEqual(Buffer.from(expected),Buffer.from(String(code)));});}
