import {esc} from './views.js';
const input=(label,name,value='',type='text',attrs='')=>`<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${attrs}></label>`;
export async function loadAdmissionForm({request,csrf,refresh,inquiryId}){
 const setup=await request('/api/v1/admin/admissions/setup'),inquiry=inquiryId?(await request(`/api/v1/admin/inquiries/${encodeURIComponent(inquiryId)}`)).inquiry:null;
 if(inquiry?.status==='converted'||inquiry?.studentRecordId)return{html:'<p class="notice">This inquiry is already converted.</p><a data-route href="/admin/inquiries">Back to inquiries</a>',bind(){}};
 const course=setup.courses.find(c=>c.name.toUpperCase()===inquiry?.course?.toUpperCase()),today=new Date().toISOString().slice(0,10),key=crypto.randomUUID();
 const field=(label,name,value='',type='text',attrs='')=>input(label,name,value,type,attrs);
 return{html:`<div class="page-intro"><div><p class="eyebrow">ADMISSIONS</p><h1>${inquiry?'Convert inquiry to admission':'New admission'}</h1><p class="muted">Student ID will be assigned when the admission is saved.${inquiry?` Inquiry ${esc(inquiry.inquiryNo)} remains linked.`:''}</p></div><a data-route class="button" href="/admin/${inquiry?'inquiries':'admissions'}">Back</a></div><section class="panel detail-panel"><div id="admission-error" role="alert"></div>${!setup.courses.length?'<p class="notice">Admission course setup is required before creating students.</p>':''}<form id="admission-form"><div class="form-grid">${field('Full name','name',inquiry?.name||'','text','required maxlength="120"')}${field('Mobile','mobile',inquiry?.mobile||'','tel','required pattern="[0-9]{10}" maxlength="10"')}${field('Guardian name','guardian',inquiry?.guardian||'')}${field('Mother name','motherName')}<label>Course<select name="courseId" required><option value="">Select course</option>${setup.courses.map(c=>`<option value="${esc(c.id)}" ${course?.id===c.id?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Batch<select name="batch"><option value="">No batch</option>${setup.batches.map(b=>`<option value="${esc(b.batch)}">${esc(b.batch)} · ${b.capacity} seats</option>`).join('')}</select></label>${field('Admission date','admissionDate',today,'date','required')}${field('Exam session','session',`July ${today.slice(2,4)}-${String(Number(today.slice(0,4))+1).slice(-2)}`)}<label>Status<select name="status"><option>active</option><option>completed</option><option>left</option></select></label>${field('Course fee (₹)','fee',course?.fee??0,'number','required min="0" step="0.01"')}${field('Discount (₹)','discount',0,'number','min="0" step="0.01"')}<label><span>CVRU add-on</span><input name="addonEnabled" type="checkbox"></label>${field('Add-on fee (₹)','addonFee',0,'number','min="0" step="0.01"')}${field('CVRU registration number','cvruRegNo','','text','maxlength="30"')}${field('ABC ID','abcId','','text','maxlength="30"')}${field('DEB ID','debId','','text','maxlength="30"')}<label class="wide">Address<textarea name="address" maxlength="500">${esc(inquiry?.message||'')}</textarea></label></div><h2>Installments</h2><p class="muted">Leave empty to create monthly installments from the course duration. You can add a custom plan whose total equals the net fee.</p><div id="admission-installments"></div><button type="button" id="add-installment">Add installment</button><div class="form-actions"><button class="primary" type="submit" ${setup.courses.length?'':'disabled'}>Save admission</button></div></form></section>`,bind(root){
  const form=root.querySelector('#admission-form'),alert=root.querySelector('#admission-error');
  const cvru=()=>{const selected=setup.courses.find(c=>c.id===form.elements.courseId.value),enabled=selected?.code.toUpperCase().includes('CVRU');for(const name of ['addonEnabled','addonFee','cvruRegNo','abcId','debId'])form.elements[name].disabled=!enabled;if(!enabled){form.elements.addonEnabled.checked=false;form.elements.addonFee.value='0';}};
  cvru();form.elements.courseId.addEventListener('change',()=>{form.elements.fee.value=setup.courses.find(c=>c.id===form.elements.courseId.value)?.fee||0;cvru();});
  form.elements.admissionDate.addEventListener('change',()=>{const y=Number(form.elements.admissionDate.value.slice(0,4));if(y)form.elements.session.value=`July ${String(y).slice(-2)}-${String(y+1).slice(-2)}`;});
  root.querySelector('#add-installment').addEventListener('click',()=>{const row=document.createElement('div');row.className='form-grid';row.innerHTML=`${field('Due date','planDate','','date','required')}${field('Amount (₹)','planAmount','','number','required min="0.01" step="0.01"')}${field('Remark','planRemark','','text','maxlength="500"')}<button type="button">Remove installment</button>`;row.querySelector('button').addEventListener('click',()=>row.remove());root.querySelector('#admission-installments').append(row);});
  form.addEventListener('submit',async e=>{e.preventDefault();const button=form.querySelector('[type="submit"]');button.disabled=true;alert.textContent='Saving admission…';const body=Object.fromEntries(new FormData(form));delete body.planDate;delete body.planAmount;delete body.planRemark;for(const name of ['fee','discount','addonFee'])body[name]=Number(body[name]||0);body.addonEnabled=form.elements.addonEnabled.checked;body.installments=[...root.querySelector('#admission-installments').children].map((r,i)=>({installmentNo:i+1,dueDate:r.querySelector('[name="planDate"]').value,amount:Number(r.querySelector('[name="planAmount"]').value),remark:r.querySelector('[name="planRemark"]').value}));if(inquiry)body.version=inquiry.version;
   try{const result=await request(inquiry?`/api/v1/admin/inquiries/${encodeURIComponent(inquiry.id)}/convert`:'/api/v1/admin/admissions',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf,'Idempotency-Key':key},body:JSON.stringify(body)});history.replaceState(null,'',`/admin/students?record=${encodeURIComponent(result.student.id)}`);await refresh();}catch(err){alert.textContent=err.details?.map(d=>`${d.field}: ${d.message}`).join(' ')||err.message;button.disabled=false;}
  });
 }};
}
