import { loadManagement } from "./management.js";
import { loadAcademic } from "./academic.js";
import { loadFinance } from "./finance.js";
import { loadStep6E } from "./step6e.js";
import { loadExpenses } from "./expenses.js";
import { loadReport } from "./reports.js";
import { loadSalary } from "./salary.js";
import { loadAdministration } from "./administration.js";
import { visibleNavigation } from './navigation.js';
import { dashboard, esc, placeholder, table } from './views.js';
const q=s=>document.querySelector(s);
let csrf='',challenge='',user=null,items=[],generation=0;
const media=matchMedia('(max-width: 900px)');
async function request(path,options={}){const r=await fetch(path,{...options,cache:'no-store'});const b=await r.json();if(!r.ok){const e=new Error(b.error?.message||'Request failed. Please retry.');e.status=r.status;e.details=b.error?.details;throw e;}return b;}
function authMessage(text){q('#message').textContent=text;}
function lock(message=''){document.title='FMS Admin';q('#account-menu').open=false;generation++;user=null;csrf='';challenge='';items=[];q('#content').replaceChildren();q('#navigation').replaceChildren();q('#identity-name').textContent='';q('#role-badge').textContent='';q('#workspace').hidden=true;q('#auth').hidden=false;q('#mfa').hidden=true;document.body.classList.remove('nav-open');q('#backdrop').hidden=true;authMessage(message);}
async function open(b){if(!b.user.permissions?.includes('admin:dashboard:read')){lock('This account cannot access the Admin workspace. Use the Student Portal.');return;}user=b.user;csrf=b.csrfToken||'';q('#login').reset();q('#mfa').reset();const nav=await request('/api/v1/admin/navigation');const allowed=new Set(nav.items.map(i=>i.id));items=visibleNavigation(user.permissions).filter(i=>allowed.has(i.id));q('#identity-name').textContent=user.name;q('#role-badge').textContent=user.role;q('#auth').hidden=true;q('#workspace').hidden=false;drawNav();syncToggle();await render();}
function drawNav(){let group='';q('#navigation').innerHTML=items.map(i=>{const heading=i.group!==group?`<h2>${esc(i.group)}</h2>`:'';group=i.group;return `${heading}<a data-route aria-label="${esc(i.label)}" title="${esc(i.label)}" href="${i.path}"><span aria-hidden="true">${i.icon}</span><span class="nav-label">${esc(i.label)}</span></a>`;}).join('');}
async function submit(form,handler){const button=form.querySelector('button');button.disabled=true;try{await handler();}catch(e){authMessage(e.message);}finally{button.disabled=false;}}
q('#login').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;submit(form,async()=>{authMessage('Signing inâ€¦');const b=await request('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.elements.password.value='';if(b.mfaRequired){challenge=b.challengeId;q('#mfa').hidden=false;q('#mfa input').focus();authMessage('Enter your authenticator code.');}else await open(b);});});
q('#mfa').addEventListener('submit',e=>{e.preventDefault();const form=e.currentTarget;submit(form,async()=>open(await request('/api/v1/auth/mfa/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challengeId:challenge,code:new FormData(form).get('code')})})));});
async function logout(){try{if(!csrf){lock('Sign in again to securely end this existing session.');return;}await request('/api/v1/auth/logout',{method:'POST',headers:{'X-CSRF-Token':csrf}});lock('Signed out successfully.');history.replaceState(null,'','/admin');}catch(e){q('#content').innerHTML=`<p role="alert">${esc(e.message)}</p><button id="retry-logout">Retry logout</button>`;q('#retry-logout').onclick=logout;}}
q('#logout').onclick=logout;q('#sidebar-logout').onclick=logout;
function syncToggle(){const expanded=media.matches?document.body.classList.contains('nav-open'):!document.body.classList.contains('nav-collapsed');q('#toggle').setAttribute('aria-expanded',String(expanded));q('#backdrop').hidden=!(media.matches&&expanded);q('#sidebar').inert=media.matches&&!expanded;}
function closeNav(){document.body.classList.remove('nav-open');syncToggle();}
q('#toggle').onclick=()=>{document.body.classList.toggle(media.matches?'nav-open':'nav-collapsed');syncToggle();if(media.matches&&document.body.classList.contains('nav-open'))q('#navigation a')?.focus();};q('#backdrop').onclick=closeNav;media.addEventListener('change',closeNav);
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeNav();q('#account-menu').open=false;q('#toggle').focus();}if(e.key==='Tab'&&media.matches&&document.body.classList.contains('nav-open')){const focus=[...q('#sidebar').querySelectorAll('a,button')];if(e.shiftKey&&document.activeElement===focus[0]){e.preventDefault();focus.at(-1).focus();}
else if(!e.shiftKey&&document.activeElement===focus.at(-1)){e.preventDefault();focus[0].focus();}}});
document.addEventListener('click',e=>{const a=e.target.closest('a[data-route]');if(!a||e.ctrlKey||e.metaKey||e.shiftKey||e.button!==0)return;e.preventDefault();history.pushState(null,'',a.getAttribute('href'));closeNav();q('#account-menu').open=false;render();});
addEventListener('popstate',()=>{if(user)render();});
async function render(){const ticket=++generation;const id=location.pathname.replace(/^\/admin\/?/,'')||'dashboard';const item=items.find(i=>i.id===id);q('#page-title').textContent=item?.label||'Access unavailable';q('#breadcrumb').textContent=`Workspace / ${item?.group||'Access'}`;document.title=`${item?.label||'Admin'} Â· FMS`;document.querySelectorAll('#navigation a').forEach(a=>{if(a.getAttribute('href')===(item?.path))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});q('#content').innerHTML='<div class="loading" role="status">Loading your workspaceâ€¦</div>';q('#content').focus();try{if(!item){q('#content').innerHTML=placeholder('Access unavailable','This route is unavailable for your account.');return;}let html,management;if(id==='dashboard')html=dashboard(await request('/api/v1/admin/dashboard/summary'),items);else if(id==='account')html=`<div class="page-intro"><h1>My Account</h1></div><section class="panel account-info"><h2>${esc(user.name)}</h2><p>${esc(user.userId)}</p><span class="badge">${esc(user.role)}</span><p>Secure session active. ${user.role==='admin'?'Administrator sign-in requires MFA.':''}</p><p class="muted">Account and security configuration integration is scheduled for a later step.</p></section>`;else if(['inquiries','admissions','students','left-students'].includes(id)){management=await loadManagement(id,{request,user,csrf,refresh:render});html=management.html;}
else if(['courses','sessions','batches'].includes(id)){management=await loadAcademic(id,{request,csrf,refresh:render});html=management.html;}
else if(['fees','installments','payments','dues','receipts'].includes(id)){management=await loadFinance(id,{request,csrf,refresh:render});html=management.html;}
else if(['notices','reminders','certificates','id-cards'].includes(id)){management=await loadStep6E(id,{request,csrf,refresh:render});html=management.html;}
else if(['expenses','profit-loss'].includes(id)){management=await loadExpenses(id,{request,csrf,refresh:render});html=management.html;}
else if(id.startsWith('reports/')){management=await loadReport(id.slice('reports/'.length),{request,refresh:render});html=management.html;}
else if(id==='salary'){management=await loadSalary({request,csrf,refresh:render});html=management.html;}
else if(['users','audit','settings','backup'].includes(id)){management=await loadAdministration(id,{request,csrf,refresh:render});html=management.html;}
else{const data=await request(`/api/v1/admin/modules/${encodeURIComponent(id)}`);html=placeholder(data.title,data.message);}if(ticket!==generation||!user)return;q('#content').innerHTML=html;management?.bind(q('#content'));q('#record-search')?.addEventListener('submit',e=>{e.preventDefault();const params=new URLSearchParams(location.search);params.set('query',new FormData(e.currentTarget).get('query'));history.replaceState(null,'',`${item.path}?${params}`);render();});}catch(e){if(ticket!==generation)return;if(e.status===401){lock('Your session expired. Please sign in again.');return;}q('#content').innerHTML=`<section class="panel placeholder"><h1>Unable to load this page</h1><p role="alert">${esc(e.message)}</p><button id="retry" class="primary">Retry</button></section>`;q('#retry').onclick=render;}}
// Existing API intentionally does not return CSRF secrets on GET /me. Require sign-in
// on reload so all account actions retain the existing authenticated CSRF flow.
