import {esc,money} from './views.js';
const labels={fees:'Fee Collection',installments:'Installments',payments:'Payments',dues:'Due List',receipts:'Receipts'};
export async function loadFinance(kind,{request,csrf,refresh}){const p=new URLSearchParams(location.search),data=await request(`/api/v1/admin/finance?kind=${kind}&query=${encodeURIComponent(p.get('query')||'')}`),rows=data.items;let body='';
 if(kind==='dues')body=rows.map(r=>`<tr><td>${esc(r.student.studentId)}</td><td>${esc(r.student.name)}</td><td>${esc(r.student.course)}</td><td>${esc(r.due?.dueDate||'Unscheduled')}</td><td>${money(r.due?.amountPaise??r.outstandingPaise)}</td><td>${esc(r.due?.status||'outstanding')}</td></tr>`).join('');
 else if(kind==='installments')body=rows.flatMap(r=>r.installments.map(i=>`<tr><td>${esc(r.student.studentId)}</td><td>${esc(r.student.name)}</td><td>${i.installmentNo}</td><td>${esc(i.dueDate)}</td><td>${money(i.amountPaise)}</td><td>${money(i.remainingPaise)}</td><td>${esc(i.status)}</td></tr>`)).join('');
 else if(kind==='payments'||kind==='receipts')body=rows.flatMap(r=>(kind==='payments'?r.payments:r.receipts).map(x=>`<tr><td>${esc(x.receiptNumber)}</td><td>${esc(r.student.studentId)}</td><td>${esc(r.student.name)}</td><td>${esc(x.date)}</td><td>${money(x.amountPaise)}</td><td>${esc(x.mode||x.status)}</td></tr>`)).join('');
 else body=rows.map(r=>`<tr><td>${esc(r.student.studentId)}</td><td>${esc(r.student.name)}</td><td>${esc(r.student.course)}</td><td>${money(r.totalPaise)}</td><td>${money(r.paidPaise)}</td><td>${money(r.outstandingPaise)}</td><td><button class="collect" data-id="${esc(r.student.id)}" data-max="${r.outstandingPaise}" ${r.outstandingPaise?'':'disabled'}>Collect</button></td></tr>`).join('');
 const heads=kind==='dues'?['Student ID','Name','Course','Due date','Amount','Status']:kind==='installments'?['Student ID','Name','#','Due date','Planned','Remaining','Status']:kind==='payments'||kind==='receipts'?['Receipt','Student ID','Name','Date','Amount','Mode / status']:['Student ID','Name','Course','Net payable','Paid','Outstanding','Action'];
 return{html:`<div class="page-intro"><div><p class="eyebrow">FEES & PAYMENTS</p><h1>${labels[kind]}</h1><p class="muted">Balances are derived from saved admission installments and posted payment history.</p></div><span class="source-badge">As of ${esc(data.asOf)}</span></div><form id="finance-search" class="panel filters"><input name="query" value="${esc(p.get('query')||'')}" placeholder="Student ID, name or course"><button>Search</button></form><p id="finance-alert" role="alert"></p><section class="panel"><div class="table-scroll"><table><thead><tr>${heads.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${body||`<tr><td colspan="${heads.length}" class="empty">No records found.</td></tr>`}</tbody></table></div></section>`,bind(root){root.querySelector('#finance-search').onsubmit=e=>{e.preventDefault();const q=new FormData(e.currentTarget).get('query');history.replaceState(null,'',`/admin/${kind}?query=${encodeURIComponent(q)}`);refresh()};root.querySelectorAll('.collect').forEach(b=>b.onclick=async()=>{const amount=prompt(`Payment amount (maximum ₹${(Number(b.dataset.max)/100).toFixed(2)})`);if(amount==null)return;try{await request(`/api/v1/admin/finance/students/${encodeURIComponent(b.dataset.id)}/payments`,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify({amount:Number(amount),date:new Date().toISOString().slice(0,10),mode:'Cash',reference:''})});refresh()}catch(e){root.querySelector('#finance-alert').textContent=e.message}})}};}
