import {createPostgresAdmission} from "./postgres-admission.js";
import { createPostgresManagement } from "./postgres-management.js";
import { createPostgresAcademic } from "./postgres-academic.js";
import { createPostgresFinance } from "./postgres-finance.js";
import { createPostgresStep6E } from "./postgres-step6e.js";
import { createPostgresExpenses } from "./postgres-expenses.js";
import { createPostgresReports } from "./postgres-reports.js";
import { createPostgresSalary } from "./postgres-salary.js";
import { createPostgresAdministration } from "./postgres-administration.js";
import { createPostgresStudentPortal } from "./postgres-student-portal.js";
import { createPool } from "../db/pool.js";
import { decryptSecret,sha256 } from "../lib/security-step3.js";
import {HttpError} from '../lib/http.js';

const user=(r,config)=>r?{id:r.id,userId:r.user_id,name:r.display_name,role:r.role==="superadmin"?"admin":r.role,status:r.status,studentRecordId:r.student_record_id,password:{salt:r.password_salt,digest:r.password_digest},mfaEnabled:r.mfa_enabled,mfaSecret:r.mfa_secret_ciphertext?decryptSecret(r.mfa_secret_ciphertext,config.mfaEncryptionKey):null,failedLoginCount:r.failed_login_count,lockedUntil:r.locked_until?new Date(r.locked_until).getTime():null}:null;
const student=r=>r?{id:r.id,studentId:r.student_id,name:r.display_name,course:r.course_name,batch:r.batch_name,status:r.status,admissionDate:r.admission_date,fee:{currency:"INR",totalPaise:Number(r.total_fee_paise),paidPaise:Number(r.paid_paise),duePaise:Number(r.total_fee_paise-r.paid_paise)},nextInstallment:r.next_installment_date?{dueDate:r.next_installment_date,amountPaise:Number(r.next_installment_paise)}:null}:null;
const inquiry=r=>r?{id:r.id,inquiryNo:r.inquiry_no,name:r.name,mobile:r.mobile,course:r.course,message:r.message,status:r.status,version:r.version,createdAt:r.created_at,updatedAt:r.updated_at}:null;

export function createPostgresRepository(config){const pool=createPool(config),finance=createPostgresFinance(pool);return{
 ...createPostgresManagement(pool),
 ...createPostgresAcademic(pool),
 ...createPostgresAdmission(pool),
 ...finance,
 ...createPostgresStudentPortal(pool,finance),
 ...createPostgresStep6E(pool,finance),
 ...createPostgresExpenses(pool),
 ...createPostgresReports(pool,finance),
 ...createPostgresSalary(pool),
 ...createPostgresAdministration(pool),
 kind:"postgres",async findUser(userId){const r=await pool.query("SELECT * FROM app_users WHERE normalized_user_id=$1",[String(userId).trim().toLowerCase()]);return user(r.rows[0],config)},async findUserById(id){const r=await pool.query("SELECT * FROM app_users WHERE id=$1",[id]);return user(r.rows[0],config)},
 async authLoginGuard(accountHash,ipHash){const c=await pool.connect();let blocked=false;try{await c.query('BEGIN');for(const key of [sha256(`account:${accountHash}`),sha256(`ip:${ipHash}`)]){const r=await c.query("INSERT INTO auth_throttle_buckets(throttle_key,attempts) VALUES($1,1) ON CONFLICT(throttle_key) DO UPDATE SET attempts=CASE WHEN auth_throttle_buckets.window_started_at<now()-($2*interval '1 second') THEN 1 ELSE auth_throttle_buckets.attempts+1 END,window_started_at=CASE WHEN auth_throttle_buckets.window_started_at<now()-($2*interval '1 second') THEN now() ELSE auth_throttle_buckets.window_started_at END,blocked_until=CASE WHEN auth_throttle_buckets.blocked_until>now() THEN auth_throttle_buckets.blocked_until WHEN (CASE WHEN auth_throttle_buckets.window_started_at<now()-($2*interval '1 second') THEN 1 ELSE auth_throttle_buckets.attempts+1 END)>$3 THEN now()+($4*interval '1 second') ELSE NULL END,updated_at=now() RETURNING blocked_until",[key,config.loginWindowSeconds,config.loginMaxAttempts,config.accountLockSeconds]);blocked||=Boolean(r.rows[0].blocked_until&&new Date(r.rows[0].blocked_until)>new Date())}await c.query('COMMIT')}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}if(blocked)throw new HttpError(429,'RATE_LIMITED','Too many requests. Please try again later.')},
 async authLoginFailure(id){if(id)await pool.query("UPDATE app_users SET failed_login_count=failed_login_count+1,locked_until=CASE WHEN failed_login_count+1>=5 THEN now()+($2*interval '1 second') ELSE locked_until END,updated_at=now() WHERE id=$1",[id,config.accountLockSeconds])},
 async authLoginSuccess(id){await pool.query("UPDATE app_users SET failed_login_count=0,locked_until=NULL,updated_at=now() WHERE id=$1",[id])},
 async securityCleanup(){const r=await pool.query("WITH s AS (DELETE FROM sessions WHERE expires_at<now() OR revoked_at<now()-interval '7 days' RETURNING 1),c AS (DELETE FROM mfa_challenges WHERE expires_at<now() OR consumed_at<now()-interval '1 day' RETURNING 1),t AS (DELETE FROM account_tokens WHERE expires_at<now() OR used_at<now()-interval '7 days' RETURNING 1),b AS (DELETE FROM auth_throttle_buckets WHERE updated_at<now()-interval '1 day' RETURNING 1) SELECT (SELECT count(*) FROM s)+(SELECT count(*) FROM c)+(SELECT count(*) FROM t)+(SELECT count(*) FROM b) AS removed");return Number(r.rows[0].removed)},
 async findStudent(id){const r=await pool.query("SELECT * FROM students WHERE id=$1",[id]);return student(r.rows[0])},async listStudents({query=""}={}){const r=await pool.query("SELECT * FROM students WHERE $1='' OR student_id ILIKE '%'||$1||'%' OR display_name ILIKE '%'||$1||'%' OR course_name ILIKE '%'||$1||'%' ORDER BY display_name LIMIT 100",[query]);return r.rows.map(student)},
 async createSession(x){await pool.query("INSERT INTO sessions(token_hash,csrf_hash,user_id,expires_at) VALUES($1,$2,$3,$4)",[x.tokenHash,x.csrfHash,x.userId,new Date(x.expiresAt)])},async getSession(hash){const r=await pool.query("SELECT * FROM sessions WHERE token_hash=$1 AND revoked_at IS NULL AND expires_at>now()",[hash]);const s=r.rows[0];return s?{tokenHash:s.token_hash,csrfHash:s.csrf_hash,userId:s.user_id,expiresAt:new Date(s.expires_at).getTime()}:null},async revokeSession(hash){await pool.query("UPDATE sessions SET revoked_at=now() WHERE token_hash=$1 AND revoked_at IS NULL",[hash])},
 async createChallenge(userId,expiresAt){const r=await pool.query("INSERT INTO mfa_challenges(user_id,expires_at) VALUES($1,$2) RETURNING *",[userId,new Date(expiresAt)]);return{id:r.rows[0].id,userId,expiresAt}},async getChallenge(id){const r=await pool.query("SELECT * FROM mfa_challenges WHERE id=$1 AND consumed_at IS NULL AND expires_at>now() AND attempts<5",[id]);const c=r.rows[0];return c?{id:c.id,userId:c.user_id,expiresAt:new Date(c.expires_at).getTime(),attempts:c.attempts}:null},async failChallenge(id){await pool.query("UPDATE mfa_challenges SET attempts=attempts+1 WHERE id=$1",[id])},async consumeChallenge(id){await pool.query("UPDATE mfa_challenges SET consumed_at=now() WHERE id=$1 AND consumed_at IS NULL",[id])},
 async createAccountToken(userId,kind,tokenHash,expiresAt){const client=await pool.connect();try{await client.query("BEGIN");await client.query("UPDATE account_tokens SET used_at=now() WHERE user_id=$1 AND kind=$2 AND used_at IS NULL",[userId,kind]);await client.query("INSERT INTO account_tokens(token_hash,user_id,kind,expires_at) VALUES($1,$2,$3,$4)",[tokenHash,userId,kind,new Date(expiresAt)]);await client.query("COMMIT")}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}},
 async consumeAccountToken(tokenHash,kind,password){const client=await pool.connect();try{await client.query("BEGIN");const r=await client.query("SELECT * FROM account_tokens WHERE token_hash=$1 AND kind=$2 AND used_at IS NULL AND expires_at>now() FOR UPDATE",[tokenHash,kind]);if(!r.rowCount){await client.query("ROLLBACK");return null}const rec=password;const u=await client.query("UPDATE app_users SET password_salt=$1,password_digest=$2,status='active',activated_at=COALESCE(activated_at,now()),failed_login_count=0,locked_until=NULL,updated_at=now() WHERE id=$3 RETURNING *",[rec.salt,rec.digest,r.rows[0].user_id]);await client.query("UPDATE account_tokens SET used_at=now() WHERE token_hash=$1",[tokenHash]);await client.query("UPDATE sessions SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL",[r.rows[0].user_id]);await client.query("COMMIT");return user(u.rows[0],config)}catch(e){await client.query("ROLLBACK");throw e}finally{client.release()}},
 async getIdempotency(scope,key){const r=await pool.query("SELECT * FROM idempotency_records WHERE scope=$1 AND idempotency_key=$2 AND expires_at>now()",[scope,key]);const x=r.rows[0];return x?{requestHash:x.request_hash,status:x.response_status,body:x.response_body}:null},async saveIdempotency(scope,key,requestHash,status,body){await pool.query("INSERT INTO idempotency_records(scope,idempotency_key,request_hash,response_status,response_body,expires_at) VALUES($1,$2,$3,$4,$5,now()+interval '24 hours')",[scope,key,requestHash,status,body])},
 async addInquiry(d){const no=`WEB-${Date.now()}-${Math.floor(Math.random()*1000)}`;const r=await pool.query("INSERT INTO inquiries(inquiry_no,name,mobile,course,message,consent) VALUES($1,$2,$3,$4,$5,$6) RETURNING *",[no,d.name,d.mobile,d.course,d.message,d.consent]);return inquiry(r.rows[0])},async listInquiries({status,query=""}={}){const r=await pool.query("SELECT * FROM inquiries WHERE ($1::text IS NULL OR status::text=$1) AND ($2='' OR inquiry_no ILIKE '%'||$2||'%' OR name ILIKE '%'||$2||'%' OR mobile ILIKE '%'||$2||'%' OR course ILIKE '%'||$2||'%') ORDER BY created_at DESC LIMIT 100",[status||null,query]);return r.rows.map(inquiry)},async updateInquiryStatus(id,status,version){const r=await pool.query("UPDATE inquiries SET status=$1,version=version+1,updated_at=now() WHERE id=$2 AND version=$3 RETURNING *",[status,id,version]);return inquiry(r.rows[0])},
 async audit(e){await pool.query("INSERT INTO audit_events(actor_user_id,actor_role,action,entity_type,entity_id,request_id,ip_hash,outcome,metadata) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)",[e.actorUserId||null,e.actorRole||null,e.action,e.entityType,e.entityId||"",e.requestId,e.ipHash||null,e.outcome,e.metadata||{}])},async close(){await pool.end()}
};}
