import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {createStep3App} from '../services/api/src/app-step3.js';
import {createSyntheticStep3Repository} from '../services/api/src/repositories/synthetic-step3.js';
import {loadConfig} from '../services/api/src/config-step3.js';
import {totp} from '../services/api/src/lib/security-step3.js';
import {ROLES,PERMISSIONS,hasPermission} from '../packages/domain/src/rbac-step3.js';
import {ADMIN_NAVIGATION,visibleNavigation} from '../packages/domain/src/admin-navigation.js';
import {dashboardSummary} from '../services/api/src/admin-dashboard.js';
import {esc,dashboard} from '../apps/admin-web/views.js';
async function setup(t){const config={...loadConfig(),dataSource:'synthetic',port:0,origin:'http://127.0.0.1'},repo=createSyntheticStep3Repository(config),server=createStep3App(config,repo);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());return{base:`http://127.0.0.1:${server.address().port}`,repo};}
const post=(base,path,body,headers={})=>fetch(base+path,{method:'POST',headers:{Origin:'http://127.0.0.1','Content-Type':'application/json',...headers},body:JSON.stringify(body)});
async function login(base,userId='admin@example.test'){let r=await post(base,'/api/v1/auth/login',{userId,password:userId.startsWith('STU')?'Student!123':'ChangeMe!123'});let b=await r.json();if(b.mfaRequired){assert.equal(r.status,202);r=await post(base,'/api/v1/auth/mfa/verify',{challengeId:b.challengeId,code:totp('JBSWY3DPEHPK3PXP')});b=await r.json();}assert.equal(r.status,200);return{body:b,headers:{Cookie:r.headers.get('set-cookie').split(';')[0]}};}
test('Step 6A active roles transfer all privileged permissions without elevating staff',()=>{assert.deepEqual(ROLES,['admin','staff','student']);assert.equal(hasPermission({role:'superadmin'},'system:admin'),false);assert.ok(PERMISSIONS.admin.includes('system:admin'));assert.ok(PERMISSIONS.admin.includes('audit:read'));assert.equal(PERMISSIONS.staff.includes('system:admin'),false);assert.equal(PERMISSIONS.staff.includes('audit:read'),false);assert.equal(visibleNavigation(PERMISSIONS.student).length,0);});
test('Step 6A migrated synthetic account keeps identity and MFA',async t=>{const{base}=await setup(t);const session=await login(base,'superadmin@example.test');assert.equal(session.body.user.id,'usr-super');assert.equal(session.body.user.role,'admin');assert.ok(session.body.user.permissions.includes('system:admin'));assert.equal(JSON.stringify(session.body.user).includes('mfaSecret'),false);});
test('Step 6A dashboard rejects anonymous and student access and filters staff financial data',async t=>{const{base}=await setup(t);assert.equal((await fetch(base+'/api/v1/admin/dashboard/summary')).status,401);const student=await login(base,'STU-DEMO-001');for(const p of ['dashboard/summary','navigation','modules/backup'])assert.equal((await fetch(base+'/api/v1/admin/'+p,{headers:student.headers})).status,403);const staff=await login(base,'staff@example.test');const response=await fetch(base+'/api/v1/admin/dashboard/summary',{headers:staff.headers});assert.equal(response.status,200);const body=await response.json();assert.equal(body.counts.totalStudents,2);assert.equal(body.collections.totalDue,null);assert.deepEqual(body.recentPayments,[]);assert.deepEqual(body.upcomingDues,[]);});
test('Step 6A server navigation and every module enforce shared permissions',async t=>{const{base}=await setup(t);for(const id of ['admin@example.test','staff@example.test']){const s=await login(base,id);const nav=await(await fetch(base+'/api/v1/admin/navigation',{headers:s.headers})).json();assert.deepEqual(nav.items,visibleNavigation(s.body.user.permissions));for(const item of ADMIN_NAVIGATION){const r=await fetch(base+'/api/v1/admin/modules/'+encodeURIComponent(item.id),{headers:s.headers});assert.equal(r.status,s.body.user.permissions.includes(item.permission)?200:403,item.id);assert.equal((await fetch(base+item.path)).status,200,item.path);}assert.equal((await fetch(base+'/api/v1/admin/modules/unknown',{headers:s.headers})).status,404);}});
test('Step 6A backend snapshot retains existing financial, cumulative due and batch values',async t=>{const{base}=await setup(t);const s=await login(base);const b=await(await fetch(base+'/api/v1/admin/dashboard/summary',{headers:s.headers})).json();assert.equal(b.source,'synthetic');assert.equal(b.collections.totalDue,2250000);assert.equal(b.collections.month,0);assert.equal(b.recentPayments.reduce((n,p)=>n+p.amountPaise,0),750000);assert.equal(b.upcomingDues[0].amountPaise,600000);assert.equal(b.upcomingDues[1].amountPaise,null);assert.equal(b.counts.certificatesIssued,0);assert.equal(b.batches[0].capacity,15);assert.equal(b.batches[0].availableSeats,14);const serialized=JSON.stringify(b);for(const secret of ['password','csrf','mfaSecret','tokenHash','audit'])assert.equal(serialized.includes(secret),false);const html=dashboard(b,visibleNavigation(PERMISSIONS.admin));for(const label of ['Recent Payments','Upcoming Dues','Course-wise Collection','Batch Summary'])assert.ok(html.includes(label));});
test('Step 6A logout revokes dashboard access and read-only views reject mutations',async t=>{const{base}=await setup(t),s=await login(base);assert.equal((await post(base,'/api/v1/admin/dashboard/summary',{},s.headers)).status,405);assert.equal((await post(base,'/api/v1/auth/logout',{},s.headers)).status,403);assert.equal((await post(base,'/api/v1/auth/logout',{},{...s.headers,'X-CSRF-Token':s.body.csrfToken})).status,200);assert.equal((await fetch(base+'/api/v1/admin/dashboard/summary',{headers:s.headers})).status,401);});
test('Step 6A PostgreSQL pending aggregates never masquerade as totals and display is escaped',async()=>{const b=await dashboardSummary({kind:'postgres',listInquiries:async()=>[],listStudents:async()=>{throw Error('Do not aggregate capped rows');}},{role:'admin'});assert.equal(b.counts.totalStudents,null);assert.equal(b.collections.totalDue,null);assert.equal(b.source,'postgres');assert.equal(esc('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');});
test('Step 6A migration preserves audit history and constrains active roles',async()=>{const sql=await readFile(new URL('../services/api/migrations/006_admin_role_migration.sql',import.meta.url),'utf8');assert.match(sql,/^BEGIN;/);assert.match(sql,/UPDATE app_users SET role='admin'/);assert.match(sql,/CHECK \(role::text IN \('admin','staff','student'\)\)/);assert.doesNotMatch(sql,/DELETE FROM|DROP TABLE|UPDATE audit_events|DISABLE TRIGGER/i);assert.match(sql,/COMMIT;/);});

test('Step 6C dashboard exposes complete independent academic aggregates',async t=>{const{base}=await setup(t);const s=await login(base);const b=await(await fetch(base+'/api/v1/admin/dashboard/summary',{headers:s.headers})).json();assert.deepEqual({totalCourses:b.counts.totalCourses,activeCourses:b.counts.activeCourses,totalSessions:b.counts.totalSessions,activeSessions:b.counts.activeSessions,totalBatches:b.counts.totalBatches,activeBatches:b.counts.activeBatches},{totalCourses:3,activeCourses:3,totalSessions:1,activeSessions:1,totalBatches:2,activeBatches:2});assert.equal(b.batches.length,2);assert.ok(b.batches.every(row=>row.course===''));const html=dashboard(b,visibleNavigation(PERMISSIONS.admin));assert.match(html,/Active Courses/);assert.match(html,/Active Sessions/);});