import test from 'node:test';import assert from 'node:assert/strict';
import {createStep3App} from '../services/api/src/app-step3.js';
import {createSyntheticStep3Repository} from '../services/api/src/repositories/synthetic-step3.js';
import {loadConfig} from '../services/api/src/config-step3.js';
import {totp} from '../services/api/src/lib/security-step3.js';
import {listOptions,validateManagementPatch} from '../packages/contracts/src/admin-management.js';
const origin='http://127.0.0.1';
async function setup(t){const config={...loadConfig(),dataSource:'synthetic',port:0,origin},repo=createSyntheticStep3Repository(config),server=createStep3App(config,repo);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());return{repo,base:`http://127.0.0.1:${server.address().port}`};}
const request=(base,path,method='GET',body,session={})=>fetch(base+'/api/v1'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...session},...(body?{body:JSON.stringify(body)}:{})});
async function login(base,userId='admin@example.test'){let r=await request(base,'/auth/login','POST',{userId,password:userId.startsWith('STU')?'Student!123':'ChangeMe!123'}),b=await r.json();if(b.mfaRequired){r=await request(base,'/auth/mfa/verify','POST',{challengeId:b.challengeId,code:totp('JBSWY3DPEHPK3PXP')});b=await r.json();}assert.equal(r.status,200);return{Cookie:r.headers.get('set-cookie').split(';')[0],'X-CSRF-Token':b.csrfToken};}
async function inquiry(repo,name='Test Inquiry'){return repo.addInquiry({name,mobile:'9999999999',course:'Office Skills',message:'Test note',consent:true});}
test('Step 6B Admin and Staff can list inquiries; anonymous and Student are denied',async t=>{const{base,repo}=await setup(t);await inquiry(repo);assert.equal((await request(base,'/admin/inquiries')).status,401);for(const user of ['admin@example.test','staff@example.test','STU-DEMO-001']){const session=await login(base,user),r=await request(base,'/admin/inquiries','GET',null,session);assert.equal(r.status,user.startsWith('STU')?403:200);}});
test('Step 6B inquiry search, exact filters, chronological sort and bounded pagination',async t=>{const{base,repo}=await setup(t);const first=await inquiry(repo,'Alpha Name');first.createdAt='2026-08-01T00:00:00Z';const second=await inquiry(repo,'Beta Name');second.createdAt='2026-09-01T00:00:00Z';await repo.updateInquiryStatus(second.id,'contacted',1);const session=await login(base,'staff@example.test');let r=await request(base,'/admin/inquiries?query=Beta&course=Office+Skills&status=contacted&from=2026-09-01&to=2026-09-01','GET',null,session);let b=await r.json();assert.equal(b.total,1);assert.equal(b.items[0].id,second.id);b=await(await request(base,'/admin/inquiries?sort=oldest&pageSize=1&page=2','GET',null,session)).json();assert.equal(b.items[0].id,second.id);assert.equal(b.total,2);b=await(await request(base,'/admin/inquiries?status=pending','GET',null,session)).json();assert.equal(b.total,2);for(const query of ['pageSize=500','page=-1','status=unknown','from=2026-02-30','from=2026-09-12&to=2026-01-01'])assert.equal((await request(base,'/admin/inquiries?'+query,'GET',null,session)).status,422);b=await(await request(base,'/admin/inquiries?query=%27%20OR%201%3D1','GET',null,session)).json();assert.equal(b.total,0);});
test('Step 6B inquiry edits validate input, preserve identity, reject stale versions and record audit',async t=>{const{base,repo}=await setup(t),row=await inquiry(repo),session=await login(base,'staff@example.test'),path='/admin/inquiries/'+row.id;for(const bad of [{name:'X',version:1},{mobile:'bad',version:1},{status:'follow-up',version:1},{password:'secret',version:1}])assert.equal((await request(base,path,'PATCH',bad,session)).status,422);let r=await request(base,path,'PATCH',{name:'Updated Name',status:'contacted',version:1},session);assert.equal(r.status,200);let b=await r.json();assert.equal(b.inquiry.id,row.id);assert.equal(b.inquiry.inquiryNo,row.inquiryNo);assert.equal(b.inquiry.version,2);assert.equal((await request(base,path,'PATCH',{status:'closed',version:1},session)).status,409);const events=await repo.listAudit();assert.ok(events.some(e=>e.action==='INQUIRY_EDIT'&&e.entityId===row.id));assert.equal((await repo.listStudents()).length,2);});
test('Step 6B mutations require CSRF and same origin; delete is unavailable',async t=>{const{base,repo}=await setup(t),row=await inquiry(repo),s=await login(base),path='/admin/inquiries/'+row.id;assert.equal((await request(base,path,'PATCH',{status:'closed',version:1},{Cookie:s.Cookie})).status,403);assert.equal((await request(base,path,'PATCH',{status:'closed',version:1},{...s,Origin:'https://untrusted.example'})).status,403);assert.equal((await request(base,path,'DELETE',null,s)).status,405);});
test('Step 6B student profile edit preserves fee, payments, installments and certificates',async t=>{const{base,repo}=await setup(t),s=await login(base),before=structuredClone(await repo.findStudent('student-demo-001')),portal=await repo.getStudentPortal('student-demo-001');const path='/admin/students/student-demo-001';const r=await request(base,path,'PATCH',{name:'Aarav Updated',mobile:'9876543210',email:'aarav.new@example.test',address:'Updated synthetic address',version:1},s);assert.equal(r.status,200);const after=await repo.findStudent('student-demo-001'),afterPortal=await repo.getStudentPortal('student-demo-001');assert.deepEqual(after.fee,before.fee);assert.deepEqual(after.nextInstallment,before.nextInstallment);for(const field of ['payments','installments','certificates','receipts'])assert.deepEqual(afterPortal[field],portal[field]);assert.equal(afterPortal.profile.mobile,'9876543210');assert.equal((await request(base,path,'PATCH',{fee:{totalPaise:0},version:2},s)).status,422);assert.equal((await request(base,path,'PATCH',{batch:'Other',version:2},s)).status,422);});
test('Step 6B Staff student access is read-only and Student cannot access admin details',async t=>{const{base}=await setup(t),staff=await login(base,'staff@example.test'),student=await login(base,'STU-DEMO-001');for(const path of ['/admin/students','/admin/students/student-demo-001'])assert.equal((await request(base,path,'GET',null,student)).status,403);const b=await(await request(base,'/admin/students/student-demo-001','GET',null,staff)).json();assert.equal(b.student.studentId,'STU-DEMO-001');assert.equal(b.student.history,undefined);assert.equal(b.student.payments,undefined);assert.equal((await request(base,'/admin/students/student-demo-001','PATCH',{name:'Unauthorized',version:1},staff)).status,403);assert.equal((await request(base,'/admin/students/student-demo-001/mark-left','POST',{version:1},staff)).status,403);assert.equal((await request(base,'/admin/admissions','GET',null,staff)).status,403);});
test('Step 6B mark-left preserves history, is safely repeatable and updates left filter/dashboard',async t=>{const{base,repo}=await setup(t),s=await login(base),before=structuredClone(await repo.findStudent('student-demo-001'));const path='/admin/students/student-demo-001/mark-left';assert.equal((await request(base,path,'POST',{version:1},s)).status,200);const second=await request(base,path,'POST',{version:1},s);assert.equal(second.status,200);assert.equal((await second.json()).unchanged,true);const list=await(await request(base,'/admin/students?status=left','GET',null,s)).json();assert.equal(list.total,1);assert.equal(list.items[0].studentId,before.studentId);assert.deepEqual(list.items[0].fee,before.fee);const dash=await(await request(base,'/admin/dashboard/summary','GET',null,s)).json();assert.equal(dash.counts.leftStudents,1);assert.equal((await repo.listAudit()).filter(e=>e.action==='STUDENT_MARK_LEFT').length,1);});
test('Step 6B audit failure rejects edit without changing state',async t=>{const{base,repo}=await setup(t),s=await login(base),before=structuredClone(await repo.findStudent('student-demo-001'));repo.audit=async()=>{throw Error('Synthetic audit unavailable');};const r=await request(base,'/admin/students/student-demo-001','PATCH',{name:'Must not persist',version:1},s);assert.equal(r.status,500);assert.deepEqual(await repo.findStudent('student-demo-001'),before);});
test('Step 6B concurrent edits permit one version only',async t=>{const{base,repo}=await setup(t),s=await login(base),row=await inquiry(repo);const results=await Promise.all(['First edit','Second edit'].map(name=>request(base,'/admin/inquiries/'+row.id,'PATCH',{name,version:1},s)));assert.deepEqual(results.map(r=>r.status).sort(),[200,409]);assert.equal((await repo.managementGet('inquiries',row.id)).version,2);});
test('Step 6B admission HTTP conversion enforces auth, CSRF, validation, idempotency and duplicate protection',async t=>{
 const{base,repo}=await setup(t),s=await login(base),staff=await login(base,'staff@example.test'),row=await inquiry(repo),path='/admin/inquiries/'+row.id+'/convert',payload={courseId:'office-demo',version:1};
 assert.equal((await request(base,'/admin/admissions/setup','GET',null,s)).status,200);
 assert.equal((await request(base,'/admin/admissions/setup','GET',null,staff)).status,403);
 assert.equal((await request(base,path,'POST',payload,staff)).status,403);
 assert.equal((await request(base,path,'POST',payload,{Cookie:s.Cookie})).status,403);
 assert.equal((await request(base,path,'POST',payload,s)).status,422);
 const headers={...s,'Idempotency-Key':'admission-test-0001'};
 assert.equal((await request(base,path,'POST',{...payload,courseId:'missing'},headers)).status,422);
 let r=await request(base,path,'POST',payload,headers);assert.equal(r.status,201);const student=(await r.json()).student;assert.equal(student.studentId,'CC-0001');assert.equal(student.inquiryId,row.id);
 r=await request(base,path,'POST',payload,headers);assert.equal(r.status,200);assert.equal((await r.json()).student.id,student.id);
 assert.equal((await request(base,path,'POST',payload,{...headers,'Idempotency-Key':'admission-test-0002'})).status,409);
 assert.equal((await request(base,'/admin/admissions','POST',{},headers)).status,409);
 assert.equal((await repo.listStudents()).length,3);assert.equal((await repo.managementGet('inquiries',row.id)).studentRecordId,student.id);
 const detail=await(await request(base,'/admin/students/'+student.id,'GET',null,s)).json();assert.ok(detail.student.history.length);assert.equal(detail.student.installments.length,1);
});

test('Step 6B student filters include mobile, session and batch',async t=>{const{base}=await setup(t),s=await login(base);const r=await request(base,'/admin/students?query=9999999999&session=2026%E2%80%9327&batch=Morning+08%3A00','GET',null,s);const b=await r.json();assert.equal(b.total,1);assert.equal(b.items[0].studentId,'STU-DEMO-001');});
test('Step 6B validation rejects unsafe types and invalid dates',()=>{assert.equal(validateManagementPatch({name:123,version:1},'students').ok,false);assert.equal(validateManagementPatch({email:'invalid',version:1},'students').ok,false);assert.equal(listOptions(new URLSearchParams('from=2026-13-01'),'students').ok,false);});
