import test from 'node:test';import assert from 'node:assert/strict';
import {createSyntheticStep3Repository} from '../services/api/src/repositories/synthetic-step3.js';import{loadConfig}from'../services/api/src/config-step3.js';
import {certificateEligibility,dueReminderCandidates,noticeRecipients} from '../packages/domain/src/step6e.js';
import {createStep3App} from '../services/api/src/app-step3.js';import{totp}from'../services/api/src/lib/security-step3.js';
import {whatsappNumber,whatsappUrl} from '../apps/admin-web/step6e.js';
import {certificateDocument,idCardDocument,code39} from '../services/api/src/step6e-documents.js';
const event={actorUserId:'usr-admin',actorRole:'admin',requestId:'step6e-test',ipHash:'test',outcome:'success'};

test('Step 6E reminders use seven-day cumulative dues, carry forward, and exclude fully paid',async()=>{const repo=createSyntheticStep3Repository(loadConfig()),rows=await repo.financeList('dues',{asOf:'2026-09-11'}),due=dueReminderCandidates(rows);assert.equal(due.length,1);assert.equal(due[0].studentRecordId,'student-demo-001');assert.equal(due[0].amountPaise,300000);assert.equal(due[0].status,'overdue');await assert.rejects(repo.step6eRecordReminder({studentRecordId:'student-demo-002',asOf:'2026-09-11'},event),x=>x.code==='REMINDER_NOT_DUE');const saved=await repo.step6eRecordReminder({studentRecordId:'student-demo-001',asOf:'2026-09-11'},event);assert.equal(saved.amountPaise,300000);assert.equal(saved.whatsappStatus,'not-requested');});

test('Step 6E manual WhatsApp links normalize Indian mobiles and encode but never auto-send',()=>{assert.equal(whatsappNumber('99999 99999'),'919999999999');assert.equal(whatsappNumber('09999999999'),'919999999999');assert.equal(whatsappNumber('123'),'');const url=whatsappUrl('9999999999','Fee due: ₹3000 & please contact us.');assert.match(url,/^https:\/\/wa\.me\/919999999999\?text=/);assert.equal(new URL(url).searchParams.get('text'),'Fee due: ₹3000 & please contact us.');assert.equal(whatsappUrl('','message'),'');});

test('Step 6E notices snapshot active, course, session and selected-student recipients with saved history',async()=>{const repo=createSyntheticStep3Repository(loadConfig()),students=await repo.listStudents();assert.equal(noticeRecipients(students,{type:'active'}).length,2);assert.equal(noticeRecipients(students,{type:'course',value:'Office & Data Skills'}).length,1);const notice=await repo.step6eCreateNotice({title:'Synthetic notice',message:'Saved portal message',target:{type:'students',studentIds:['student-demo-001']}},event);assert.equal(notice.recipientCount,1);assert.equal(notice.deliveries[0].status,'portal-saved');assert.equal(notice.deliveries[0].whatsappStatus,'not-requested');assert.equal((await repo.getStudentPortal('student-demo-001')).notices.at(-1).title,'Synthetic notice');assert.notEqual((await repo.getStudentPortal('student-demo-002')).notices.at(-1).title,'Synthetic notice');});

test('Step 6E certificate gates preserve main full payment, add-on 40/50/60, and course-end date',()=>{const common={studentStatus:'completed',courseEndDate:'2027-06-30',issueDate:'2027-06-30',totalPaise:1000000};assert.equal(certificateEligibility({...common,type:'data-entry',paidPaise:400000}).eligible,true);assert.equal(certificateEligibility({...common,type:'ms-office',paidPaise:499999}).eligible,false);assert.equal(certificateEligibility({...common,type:'ms-office',paidPaise:500000}).eligible,true);assert.equal(certificateEligibility({...common,type:'accounting-tally',paidPaise:600000}).eligible,true);assert.equal(certificateEligibility({...common,type:'main',paidPaise:999999}).eligible,false);assert.equal(certificateEligibility({...common,type:'main',paidPaise:1000000}).eligible,true);assert.match(certificateEligibility({...common,type:'main',paidPaise:1000000,issueDate:'2027-06-29'}).reason,/before the course end/i);});

test('Step 6E issue records are audited; ID cards only issue to active students and count prints',async()=>{const repo=createSyntheticStep3Repository(loadConfig()),card=await repo.step6eIssueIdCard({studentRecordId:'student-demo-001',issueDate:'2026-09-11'},event);assert.equal(card.printCount,0);const printed=await repo.step6eRecordIdCardPrint(card.id,event);assert.equal(printed.printCount,1);assert.equal(printed.status,'printed');await repo.managementUpdate('students','student-demo-002',{status:'left'},1,{...event,action:'STUDENT_MARK_LEFT',entityType:'student',entityId:'student-demo-002'});await assert.rejects(repo.step6eIssueIdCard({studentRecordId:'student-demo-002',issueDate:'2026-09-11'},event),x=>x.code==='STUDENT_NOT_ACTIVE');const actions=(await repo.listAudit()).map(x=>x.action);assert.ok(actions.includes('ID_CARD_ISSUE'));assert.ok(actions.includes('ID_CARD_PRINT_RECORD'));});

test('approved print layouts project document fields, escape data, and produce Code 39 bars',()=>{const model={studentName:'Aarav <Demo>',studentId:'CC-1063',course:'Hindi Typing',batch:'Morning',mobile:'9999999999',issueDate:'2026-09-11',validTill:'2027-06-30',trainingStart:'2026-08-01',trainingEnd:'2026-09-01',certificateNumber:'CERT-0002',guardian:'Parent & Guardian',institute:{name:'Create Computer',address:'Rajnandgaon',phone:'7000492856'}};const certificate=certificateDocument(model),card=idCardDocument(model);assert.match(certificate,/Certificate of Achievement/);assert.match(certificate,/Aarav &lt;Demo&gt;/);assert.match(certificate,/CERT-0002/);assert.match(certificate,/class="barcode"/);assert.doesNotMatch(certificate,/Aarav <Demo>/);assert.match(card,/85\.6mm|document-print\.css/);assert.match(card,/Valid Till/);assert.match(card,/STUDENTS <em>ID CARD/);assert.ok((code39('CERT-0002').match(/<rect/g)||[]).length>20)});

test('Step 6E API is admin-only and mutations require same-origin CSRF',async t=>{const origin='http://127.0.0.1',config={...loadConfig(),origin,port:0},repo=createSyntheticStep3Repository(config),server=createStep3App(config,repo);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}`,send=(path,method='GET',body,headers={})=>fetch(base+'/api/v1'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',...headers},...(body?{body:JSON.stringify(body)}:{})});assert.equal((await send('/admin/step6e?kind=notices')).status,401);let r=await send('/auth/login','POST',{userId:'admin@example.test',password:'ChangeMe!123'}),b=await r.json();r=await send('/auth/mfa/verify','POST',{challengeId:b.challengeId,code:totp('JBSWY3DPEHPK3PXP')});b=await r.json();const cookie=r.headers.get('set-cookie').split(';')[0],headers={Cookie:cookie,'X-CSRF-Token':b.csrfToken};assert.equal((await send('/admin/step6e?kind=reminders','GET',null,{Cookie:cookie})).status,200);assert.equal((await send('/admin/step6e/id-cards','POST',{studentRecordId:'student-demo-001',issueDate:'2026-09-11'},{Cookie:cookie})).status,403);assert.equal((await send('/admin/step6e/notices','POST',{title:'API notice',message:'Saved',target:{type:'active'}},headers)).status,201);});

test('Step 6E migration preserves controlled integration boundaries',async()=>{const{readFile}=await import('node:fs/promises'),sql=await readFile(new URL('../services/api/migrations/011_communications_certificates_id_cards.sql',import.meta.url),'utf8');for(const name of ['admin_notices','admin_notice_recipients','due_reminder_history','certificates','id_card_issues'])assert.match(sql,new RegExp(`CREATE TABLE ${name}`));assert.match(sql,/not-requested/);assert.match(sql,/authoritative-layout-pending/);assert.doesNotMatch(sql,/whatsapp.*url|twilio|pdf/i);});
