import test from"node:test";import assert from"node:assert/strict";import{createStep3App}from"../services/api/src/app-step3.js";import{loadConfig}from"../services/api/src/config-step3.js";import{createSyntheticStep3Repository}from"../services/api/src/repositories/synthetic-step3.js";import{totp}from"../services/api/src/lib/security-step3.js";import{ROLES,PERMISSIONS}from"../packages/domain/src/rbac-step3.js";
async function setup(t){const config={...loadConfig(),port:0,origin:"http://127.0.0.1"},repo=createSyntheticStep3Repository(config),server=createStep3App(config,repo);await new Promise(r=>server.listen(0,"127.0.0.1",r));t.after(()=>server.close());return{base:`http://127.0.0.1:${server.address().port}`,repo}}
const post=(base,path,body,extra={})=>fetch(base+path,{method:"POST",headers:{"Content-Type":"application/json",Origin:"http://127.0.0.1",...extra},body:JSON.stringify(body)});
async function login(base,id,password){const r=await post(base,"/api/v1/auth/login",{userId:id,password}),body=await r.json();return{r,body,cookie:r.headers.get("set-cookie")?.split(";")[0]}}
async function privileged(base){const first=await login(base,"admin@example.test","ChangeMe!123");assert.equal(first.r.status,202);const r=await post(base,"/api/v1/auth/mfa/verify",{challengeId:first.body.challengeId,code:totp("JBSWY3DPEHPK3PXP")});const body=await r.json();return{r,body,cookie:r.headers.get("set-cookie")?.split(";")[0]}}
test("permission matrix defines exactly three roles",()=>{assert.deepEqual(ROLES,["admin","staff","student"]);for(const r of ROLES)assert.ok(PERMISSIONS[r]);assert.equal(PERMISSIONS.student.includes("inquiry:update"),false)});
test("privileged login requires valid MFA and challenge is single use",async t=>{const{base}=await setup(t),first=await login(base,"admin@example.test","ChangeMe!123");assert.equal(first.r.status,202);const bad=await post(base,"/api/v1/auth/mfa/verify",{challengeId:first.body.challengeId,code:"000000"});assert.equal(bad.status,401);const good=await post(base,"/api/v1/auth/mfa/verify",{challengeId:first.body.challengeId,code:totp("JBSWY3DPEHPK3PXP")});assert.equal(good.status,200);const replay=await post(base,"/api/v1/auth/mfa/verify",{challengeId:first.body.challengeId,code:totp("JBSWY3DPEHPK3PXP")});assert.equal(replay.status,401)});
test("activation and recovery tokens are single-use and strengthen passwords",async t=>{const{base}=await setup(t);const request=await post(base,"/api/v1/auth/student/activation/request",{userId:"STU-ACT-002"});const token=(await request.json()).syntheticToken;assert.ok(token);const weak=await post(base,"/api/v1/auth/student/activation/confirm",{token,password:"password"});assert.equal(weak.status,422);const done=await post(base,"/api/v1/auth/student/activation/confirm",{token,password:"StrongDemo!234"});assert.equal(done.status,200);const replay=await post(base,"/api/v1/auth/student/activation/confirm",{token,password:"AnotherStrong!234"});assert.equal(replay.status,400);const signed=await login(base,"STU-ACT-002","StrongDemo!234");assert.equal(signed.r.status,200)});
test("persistent-style idempotency rejects key reuse with changed payload",async t=>{const{base}=await setup(t),key="inquiry-key-001",body={name:"Test Parent",mobile:"+919876543210",course:"Office Skills",message:"Call",consent:true};const first=await post(base,"/api/v1/inquiries",body,{"Idempotency-Key":key});assert.equal(first.status,201);const same=await post(base,"/api/v1/inquiries",body,{"Idempotency-Key":key});assert.equal(same.status,201);const conflict=await post(base,"/api/v1/inquiries",{...body,name:"Changed Parent"},{"Idempotency-Key":key});assert.equal(conflict.status,409)});
test("admin inquiry and student workflows enforce session, RBAC, CSRF and version",async t=>{const{base}=await setup(t);await post(base,"/api/v1/inquiries",{name:"Admin Queue Test",mobile:"9876543210",course:"Foundations",message:"",consent:true},{"Idempotency-Key":"admin-queue-001"});const admin=await privileged(base);const list=await fetch(base+"/api/v1/admin/inquiries",{headers:{Cookie:admin.cookie}}),items=(await list.json()).items;assert.equal(list.status,200);const patch=await fetch(base+`/api/v1/admin/inquiries/${items[0].id}`,{method:"PATCH",headers:{Cookie:admin.cookie,Origin:"http://127.0.0.1","X-CSRF-Token":admin.body.csrfToken,"Content-Type":"application/json"},body:JSON.stringify({status:"contacted",version:1})});assert.equal(patch.status,200);const stale=await fetch(base+`/api/v1/admin/inquiries/${items[0].id}`,{method:"PATCH",headers:{Cookie:admin.cookie,Origin:"http://127.0.0.1","X-CSRF-Token":admin.body.csrfToken,"Content-Type":"application/json"},body:JSON.stringify({status:"closed",version:1})});assert.equal(stale.status,409);const students=await fetch(base+"/api/v1/admin/students?query=Aarav",{headers:{Cookie:admin.cookie}});assert.equal(students.status,200);assert.equal((await students.json()).items.length,1)});
test("security activity is stored as immutable synthetic audit events",async t=>{const{base,repo}=await setup(t);await login(base,"STU-DEMO-001","Student!123");const events=await repo.listAudit();assert.equal(events.some(e=>e.action==="AUTH_LOGIN"&&e.outcome==="success"),true);assert.equal(Object.isFrozen(events[0]),true)});
test("production sessions use a __Host cookie with Secure, Strict and Priority flags",async t=>{const baseConfig=loadConfig(),config={...baseConfig,production:true,port:0,origin:'https://fms.example.test'},repo=createSyntheticStep3Repository(config),server=createStep3App(config,repo);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>server.close());const base=`http://127.0.0.1:${server.address().port}`,r=await fetch(base+'/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json',Origin:config.origin},body:JSON.stringify({userId:'STU-DEMO-001',password:'Student!123'})}),cookie=r.headers.get('set-cookie');assert.equal(r.status,200);assert.match(cookie,/^__Host-fms_session=/);assert.match(cookie,/HttpOnly/);assert.match(cookie,/SameSite=Strict/);assert.match(cookie,/Priority=High/);assert.match(cookie,/Secure/)});
test("security hardening migration adds persistent throttling without weakening immutable audit",async()=>{const{readFile}=await import('node:fs/promises'),sql=await readFile(new URL('../services/api/migrations/016_security_hardening.sql',import.meta.url),'utf8');assert.match(sql,/CREATE TABLE auth_throttle_buckets/);assert.match(sql,/throttle_key char\(64\) PRIMARY KEY/);assert.match(sql,/blocked_until timestamptz/)});
