export const sections = [['dashboard','Overview'],['profile','My profile'],['course','Course & batch'],['fees','Fee summary'],['installments','Installments'],['payments','Payment history'],['receipts','Receipts'],['dues','Dues & next payment'],['notices','Notices'],['certificates','Certificates'],['assignments','Assignments'],['projects','Project topics'],['practical','Practical work'],['credentials','Credentials'],['support','Help & contact'],['account','Account & security']];
export const escape = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const text=value=>value===null||value===undefined||value===''?'Not available':escape(value);
const currency=new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR'});
export const money=value=>Number.isSafeInteger(value)?currency.format(value/100):'Not available';
const card=(label,value,hint='')=>`<article class="metric"><span>${escape(label)}</span><strong>${text(value)}</strong>${hint?`<small>${escape(hint)}</small>`:''}</article>`;
const details=rows=>`<dl class="details">${rows.map(([label,value])=>`<div><dt>${escape(label)}</dt><dd>${text(value)}</dd></div>`).join('')}</dl>`;
const empty=message=>`<div class="empty"><h2>Nothing to show yet</h2><p>${escape(message)}</p></div>`;
const table=(head,rows)=>rows.length?`<div class="table-wrap" role="region" aria-label="${escape(head.join(', '))}" tabindex="0"><table><thead><tr>${head.map(x=>`<th scope="col">${escape(x)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${row.map(cell=>`<td>${cell}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:empty('No records are available for your account.');
const pending='<span class="badge muted">Integration pending</span>';
const receiptButton=id=>`<button class="secondary" data-receipt="${escape(id)}">Check document</button>`;
export function renderStudentPage(section,s,p={}) {
 const profile=p.profile||{},course=p.course||{},fee=p.fee||{},dues=p.dues||{};
 const feeRows=[['Course fee',money(fee.courseFeePaise)],['CVRU Add ON fee',money(fee.addOnFeePaise)],['Discount',money(fee.discountPaise)],['Net payable',money(s.fee?.totalPaise)],['Total paid',money(s.fee?.paidPaise)],['Balance due',money(s.fee?.duePaise)],['Payment status',fee.paymentStatus]];
 if(section==='dashboard')return `<div class="welcome"><div><p class="eyebrow">YOUR LEARNING JOURNEY</p><h2>Welcome, ${escape(s.name)}.</h2><p>Your course, payments and updates in one place.</p></div><a class="button" href="#/course">View my course →</a></div><div class="metrics">${card('Student ID',s.studentId)}${card('Course',s.course,profile.session||'Session unavailable')}${card('Batch',s.batch)}${card('Course status',s.status)}${card('Net payable',money(s.fee?.totalPaise))}${card('Total paid',money(s.fee?.paidPaise))}${card('Balance due',money(s.fee?.duePaise))}${card('Next installment',s.nextInstallment?.dueDate,`Planned amount: ${money(s.nextInstallment?.amountPaise)}`)}</div><div class="grid two"><article class="panel"><p class="eyebrow">STAY ON TRACK</p><h2>Your next payment</h2><p>Current scheduled due: <strong>${money(dues.currentDuePaise)}</strong></p><p>${text(dues.reminder)}</p><a href="#/dues">View dues →</a></article><article class="panel"><p class="eyebrow">YOUR UPDATES</p><h2>Notices & certificates</h2><p>Unread notices: <strong>${text(p.unreadNoticeCount)}</strong></p><p>Main certificate: ${text(p.certificates?.[0]?.eligibility)}</p><div class="actions"><a href="#/notices">Read notices →</a><a href="#/certificates">Certificate status →</a></div></article></div>`;
 if(section==='profile')return `<article class="panel"><h2>Personal & admission details</h2><p>Read-only information. Contact the institute to request a correction.</p>${details([['Student ID',s.studentId],['Full name',s.name],['Mobile',profile.mobile],['Email',profile.email],['Address',profile.address],['Course',s.course],['Session',profile.session],['Batch',s.batch],['Admission date',s.admissionDate],['Course start',profile.courseStartDate],['Course end',profile.courseEndDate],['Student status',s.status]])}<p class="muted">No approved profile photograph is available.</p></article>`;
 if(section==='course')return `<article class="panel"><p class="eyebrow">MY COURSE</p><h2>${escape(s.course)}</h2>${details([['Course name',s.course],['Course code',course.code],['Course group',course.group],['Session',course.session],['Duration',course.duration],['Batch',s.batch],['Batch time',course.batchTime],['Batch status',course.batchStatus],['Start date',course.startDate],['End date',course.endDate]])}<p class="muted">Syllabus information has not been provided.</p></article>`;
 if(section==='fees')return `<div class="metrics">${card('Net payable',money(s.fee?.totalPaise))}${card('Paid so far',money(s.fee?.paidPaise))}${card('Balance due',money(s.fee?.duePaise))}</div><article class="panel"><h2>Your fee breakdown</h2>${details(feeRows)}<p class="note">Net payable = course fee + CVRU Add ON fee − discount. All amounts are supplied by the server; this portal does not recalculate your fees.</p><a href="#/payments">View payment history →</a></article>`;
 if(section==='installments')return `<article class="panel"><h2>Your custom installment plan</h2><p>Remaining amounts are cumulative and include earlier shortages. They are not amounts to add together.</p>${table(['No.','Due date','Planned amount','Cumulative plan','Paid against cumulative plan','Remaining cumulative','Status'],(p.installments||[]).map(i=>[text(i.number),text(i.dueDate),money(i.plannedPaise),money(i.cumulativePlannedPaise),money(i.cumulativePaidPaise),money(i.remainingPaise),text(i.status)]))}</article>`;
 if(section==='payments')return `<article class="panel"><h2>Posted payment history</h2><p>Payments are read-only. For a correction or payment query, contact the institute.</p>${table(['Receipt','Date','Amount','Mode','Reference','Status','Receipt action'],(p.payments||[]).map(i=>[text(i.receiptNumber),text(i.date),money(i.amountPaise),text(i.mode),text(i.reference),text(i.status),receiptButton(i.documentId)]))}</article>`;
 if(section==='receipts')return `<article class="panel"><h2>Your receipts</h2><p>Secure document generation is pending. No downloadable receipt is available in this step.</p>${table(['Receipt','Date','Amount','Document','Action'],(p.receipts||[]).map(i=>[text(i.receiptNumber),text(i.date),money(i.amountPaise),pending,receiptButton(i.id)]))}<p id="document-status" role="status"></p></article>`;
 if(section==='dues')return `<div class="metrics">${card('Balance due',money(s.fee?.duePaise))}${card('Currently due',money(dues.currentDuePaise))}${card('Next due date',dues.nextDueDate)}${card('Next cumulative due',money(dues.nextCumulativeDuePaise))}</div><article class="panel"><h2>Plan your next payment</h2>${details([['Overdue status',dues.overdue===true?'Overdue':dues.overdue===false?'Not overdue':null],['Days overdue',dues.daysOverdue],['Days until next due',dues.daysRemaining],['Snapshot date',p.asOf]])}<p class="note">${text(dues.reminder)}</p><p>Online payment is not available. Contact the institute about payment arrangements.</p><a href="#/installments">View custom schedule →</a></article>`;
 if(section==='notices')return (p.notices||[]).length?`<div class="stack">${p.notices.map(n=>`<article class="panel"><span class="badge">${n.readAt?'Read':'Unread'}</span><time>${text(n.date)}</time><h2>${escape(n.title)}</h2><p>${escape(n.description)}</p>${n.readAt?`<p class="muted">Read: ${escape(n.readAt)}</p>`:`<button data-notice="${escape(n.id)}">Mark as read</button>`}</article>`).join('')}</div>`:empty('No notices are available for your account.');
 if(section==='certificates')return `<p class="note">Certificates are never issued automatically by this portal. Payment thresholds alone do not establish eligibility.</p><div class="grid two">${(p.certificates||[]).map(c=>`<article class="panel"><span class="badge">${c.issued?'Issued':'Not issued'}</span><h2>${escape(c.type)}</h2><p>${escape(s.course)}</p>${details([['Eligibility',c.eligibility],['Certificate number',c.number],['Issue date',c.issueDate],['Payment threshold',c.thresholdPercent===null?'Completion + full fee':`${c.thresholdPercent}%`]])}<p>${escape(c.reason)}</p>${pending}<p class="muted">Secure verification/view integration pending.</p></article>`).join('')||empty('Certificate information is not available yet.')}</div>`;
 if(['assignments','projects','practical'].includes(section)){const type={assignments:'assignment',projects:'project',practical:'practical'}[section],items=(p.resources||[]).filter(r=>r.type===type);return items.length?`<div class="grid two">${items.map(r=>`<article class="panel"><p class="eyebrow">${escape(r.type)}</p><h2>${escape(r.title)}</h2>${details([['Course',r.courseCode],['Session',r.session],['Date',r.date]])}<p>${escape(r.description)}</p><span class="badge muted">View / download pending</span></article>`).join('')}</div>`:empty('No resources are available for your course and session.');}
 if(section==='credentials')return `<article class="panel"><h2>Credentials are protected</h2><p>${text(p.credentials?.message||'Secure re-authentication and audited reveal integration are pending.')}</p>${pending}</article>`;
 if(section==='support')return `<div class="grid two"><article class="panel"><p class="eyebrow">WE’RE HERE TO HELP</p><h2>CREATE COMPUTER</h2><address>Govt. Digvijay College Road<br>Near Durga Mandir, Kilapara<br>Rajnandgaon (C.G.)</address><p><a href="tel:+917000492856">+91 7000492856</a></p><a class="button" href="https://wa.me/917000492856">Contact on WhatsApp ↗</a></article><article class="panel"><h2>Before you contact us</h2><p>Keep your student ID and relevant receipt number ready. Ask the institute about profile corrections, fees, course schedules or certificates.</p><p>Never share your password or account recovery token. Please call to confirm office timings.</p></article></div>`;
 if(section==='account')return `<article class="panel"><h2>Account & security</h2><p>You are signed in as ${escape(s.studentId)}. Your session uses the existing secure account system.</p><p>Passwords, tokens and student documents are not stored in browser storage. Sign out when using a shared device.</p><p>Password recovery uses the existing recovery flow. Completing recovery revokes prior sessions.</p><button id="recover-entry" class="secondary">Sign out & open account recovery</button></article>`;
 return empty('This section could not be found. Choose a section from the navigation.');
}
