import { adminManagementRoute } from "./admin-management-routes.js";
import { academicRoute } from "./academic-routes.js";
import { adminDashboardRoute } from "./admin-dashboard.js";
import { financeRoute } from "./finance-routes.js";
import { step6eRoute } from "./step6e-routes.js";
import { expenseRoute } from "./expense-routes.js";
import { reportRoute } from "./report-routes.js";
import { salaryRoute } from "./salary-routes.js";
import { administrationRoute } from "./administration-routes.js";
import { studentPortalRoute } from './student-portal-routes.js';
import { createServer } from "node:http";import{readFile}from"node:fs/promises";import{extname,join,normalize}from"node:path";import{randomBytes,randomUUID}from"node:crypto";import{fileURLToPath}from"node:url";
import {isIP} from 'node:net';
import{hasPermission,PERMISSIONS}from"../../../packages/domain/src/rbac-step3.js";import{validateInquiry,validateLogin}from"../../../packages/contracts/src/validation.js";import{HttpError,readJson,requestId,securityHeaders,sendJson,cookieMap}from"./lib/http.js";import{createRateLimiter,requireSameOrigin}from"./lib/security.js";import{makePasswordRecord,sha256,strongPassword,verifyPassword,verifyTotp}from"./lib/security-step3.js";
const root=fileURLToPath(new URL("../../..",import.meta.url)),mime={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".yaml":"application/yaml; charset=utf-8"};
const privileged=new Set(["admin"]),safeUser=u=>({id:u.id,userId:u.userId,name:u.name,role:u.role,permissions:PERMISSIONS[u.role]});
export function createStep3App(config,repo){const loginLimit=createRateLimiter({limit:config.loginMaxAttempts||8,windowMs:(config.loginWindowSeconds||900)*1000}),publicLimit=createRateLimiter({limit:5,windowMs:600000});const tokenHash=t=>sha256(t,config.tokenPepper);const clientIp=req=>{const remote=String(req.socket.remoteAddress||'unknown').replace(/^::ffff:/,'');if(!config.trustProxy||!config.trustedProxyAddresses?.includes(remote))return remote;const forwarded=String(req.headers['x-forwarded-for']||'').split(',')[0].trim();return isIP(forwarded)?forwarded:remote};const ipHash=req=>sha256(clientIp(req),config.auditIpPepper);const cookieName=config.production?'__Host-fms_session':'fms_session',cookieFlags=`Path=/; HttpOnly; SameSite=Strict; Priority=High; Max-Age=${config.sessionTtlSeconds}${config.production?"; Secure":""}`;
 async function audit(req,id,data){await repo.audit({...data,requestId:id,ipHash:ipHash(req)}).catch(e=>console.error(JSON.stringify({level:"error",requestId:id,message:"Audit insert failed",detail:e.message})))}
 async function issue(user){const token=randomBytes(32).toString("base64url"),csrf=randomBytes(24).toString("base64url");await repo.createSession({tokenHash:tokenHash(token),csrfHash:tokenHash(csrf),userId:user.id,expiresAt:Date.now()+config.sessionTtlSeconds*1000});return{csrf,cookie:`${cookieName}=${token}; ${cookieFlags}`}}
 async function auth(req){const token=cookieMap(req.headers.cookie)[cookieName];if(!token)throw new HttpError(401,"UNAUTHENTICATED","Authentication is required.");const session=await repo.getSession(tokenHash(token));if(!session)throw new HttpError(401,"UNAUTHENTICATED","Authentication is required.");const user=await repo.findUserById(session.userId);if(!user||user.status!=="active")throw new HttpError(401,"UNAUTHENTICATED","Authentication is required.");return{user,session,tokenHash:tokenHash(token)}}
 function allow(user,permission){if(!hasPermission(user,permission))throw new HttpError(403,"FORBIDDEN","You do not have permission for this action.")}
 function csrf(req,session){const v=String(req.headers["x-csrf-token"]||"");if(!v||tokenHash(v)!==session.csrfHash)throw new HttpError(403,"CSRF_REJECTED","CSRF token is missing or invalid.")}
 async function json(req){return readJson(req,config.maxBodyBytes)}
 async function api(req,res,url,id){
  if(await administrationRoute(req,res,url,id,{repo,auth,allow,csrf,requireSameOrigin,config,json,ipHash}))return;
  if(await salaryRoute(req,res,url,id,{repo,auth,allow,csrf,requireSameOrigin,config,json,ipHash}))return;
  if(await reportRoute(req,res,url,{repo,auth,allow}))return;
  if(await expenseRoute(req,res,url,id,{repo,auth,allow,csrf,requireSameOrigin,config,json,ipHash}))return;
  if(await step6eRoute(req,res,url,id,{repo,auth,allow,csrf,requireSameOrigin,config,json,ipHash}))return;
  if(await financeRoute(req,res,url,id,{repo,auth,allow,csrf,requireSameOrigin,config,json,ipHash}))return;
  if(await academicRoute(req,res,url,id,{repo,auth,allow,csrf,requireSameOrigin,config,json,ipHash}))return;
  if(await adminManagementRoute(req,res,url,id,{repo,auth,allow,csrf,requireSameOrigin,config,json,ipHash}))return;
  if(await adminDashboardRoute(req,res,url,{repo,auth,allow}))return;
  if(await studentPortalRoute(req,res,url,id,{repo,auth,csrf,requireSameOrigin,config,audit}))return;
  if(req.method==="GET"&&url.pathname==="/api/v1/health")return sendJson(res,200,{status:"ok",dataSource:repo.kind,version:"0.3.0"});
  if(req.method==="POST"&&url.pathname==="/api/v1/auth/login"){requireSameOrigin(req,config);const requestIpHash=ipHash(req);loginLimit(requestIpHash);const p=validateLogin(await json(req));if(!p.ok)throw new HttpError(422,"VALIDATION_FAILED","Login data is invalid.",p.errors);if(repo.authLoginGuard)await repo.authLoginGuard(sha256(p.value.userId.trim().toLowerCase(),config.tokenPepper),requestIpHash);const u=await repo.findUser(p.value.userId),locked=u?.lockedUntil&&u.lockedUntil>Date.now();if(!u||u.status!=="active"||locked||!verifyPassword(p.value.password,u.password)){if(u&&!locked&&repo.authLoginFailure)await repo.authLoginFailure(u.id);await audit(req,id,{actorUserId:u?.id,actorRole:u?.role,action:"AUTH_LOGIN",entityType:"user",entityId:u?.id,outcome:"failure"});throw new HttpError(401,"INVALID_CREDENTIALS","User ID or password is incorrect.")}if(repo.authLoginSuccess)await repo.authLoginSuccess(u.id);if(privileged.has(u.role)){if(!u.mfaEnabled)throw new HttpError(403,"MFA_ENROLLMENT_REQUIRED","Privileged accounts require MFA enrollment.");const c=await repo.createChallenge(u.id,Date.now()+config.mfaChallengeTtlSeconds*1000);return sendJson(res,202,{mfaRequired:true,challengeId:c.id})}const issued=await issue(u);await audit(req,id,{actorUserId:u.id,actorRole:u.role,action:"AUTH_LOGIN",entityType:"user",entityId:u.id,outcome:"success"});return sendJson(res,200,{user:safeUser(u),csrfToken:issued.csrf},{"Set-Cookie":issued.cookie})}
  if(req.method==="POST"&&url.pathname==="/api/v1/auth/mfa/verify"){requireSameOrigin(req,config);loginLimit(ipHash(req));const b=await json(req),c=await repo.getChallenge(String(b.challengeId||""));if(!c)throw new HttpError(401,"INVALID_MFA_CHALLENGE","MFA challenge is invalid or expired.");const u=await repo.findUserById(c.userId);if(!u||!verifyTotp(u.mfaSecret,String(b.code||""))){await repo.failChallenge(c.id);await audit(req,id,{actorUserId:u?.id,actorRole:u?.role,action:"AUTH_MFA",entityType:"user",entityId:u?.id,outcome:"failure"});throw new HttpError(401,"INVALID_MFA_CODE","MFA code is invalid.")}await repo.consumeChallenge(c.id);const issued=await issue(u);await audit(req,id,{actorUserId:u.id,actorRole:u.role,action:"AUTH_MFA",entityType:"user",entityId:u.id,outcome:"success"});return sendJson(res,200,{user:safeUser(u),csrfToken:issued.csrf},{"Set-Cookie":issued.cookie})}
  if(req.method==="POST"&&["/api/v1/auth/student/activation/request","/api/v1/auth/recovery/request"].includes(url.pathname)){requireSameOrigin(req,config);publicLimit(ipHash(req));const b=await json(req),kind=url.pathname.includes("activation")?"activation":"recovery",u=await repo.findUser(String(b.userId||""));if(u&&u.role==="student"&&(kind==="recovery"||u.status==="pending_activation")){const raw=randomBytes(32).toString("base64url"),ttl=kind==="activation"?config.activationTtlSeconds:config.recoveryTtlSeconds;await repo.createAccountToken(u.id,kind,tokenHash(raw),Date.now()+ttl*1000);await audit(req,id,{actorUserId:u.id,actorRole:u.role,action:`ACCOUNT_${kind.toUpperCase()}_REQUEST`,entityType:"user",entityId:u.id,outcome:"success"});return sendJson(res,202,{accepted:true,...(repo.kind==="synthetic"?{syntheticToken:raw}:{})})}return sendJson(res,202,{accepted:true})}
  if(req.method==="POST"&&["/api/v1/auth/student/activation/confirm","/api/v1/auth/recovery/confirm"].includes(url.pathname)){requireSameOrigin(req,config);publicLimit(ipHash(req));const b=await json(req),kind=url.pathname.includes("activation")?"activation":"recovery";if(!strongPassword(b.password))throw new HttpError(422,"WEAK_PASSWORD","Password must have 12+ characters with upper, lower, number, and symbol.");const record=makePasswordRecord(b.password),u=await repo.consumeAccountToken(tokenHash(String(b.token||"")),kind,record);if(!u)throw new HttpError(400,"INVALID_ACCOUNT_TOKEN","Token is invalid, expired, or already used.");await audit(req,id,{actorUserId:u.id,actorRole:u.role,action:`ACCOUNT_${kind.toUpperCase()}_CONFIRM`,entityType:"user",entityId:u.id,outcome:"success"});return sendJson(res,200,{activated:true})}
  if(req.method==="POST"&&url.pathname==="/api/v1/auth/logout"){requireSameOrigin(req,config);const a=await auth(req);csrf(req,a.session);await repo.revokeSession(a.tokenHash);await audit(req,id,{actorUserId:a.user.id,actorRole:a.user.role,action:"AUTH_LOGOUT",entityType:"user",entityId:a.user.id,outcome:"success"});return sendJson(res,200,{ok:true},{"Set-Cookie":`${cookieName}=; Path=/; HttpOnly; SameSite=Strict; Priority=High; Max-Age=0${config.production?"; Secure":""}`})}
  if(req.method==="GET"&&url.pathname==="/api/v1/me"){const a=await auth(req);return sendJson(res,200,{user:safeUser(a.user)})}
  if(req.method==="POST"&&url.pathname==="/api/v1/inquiries"){requireSameOrigin(req,config);publicLimit(ipHash(req));const key=String(req.headers["idempotency-key"]||"");if(!/^[A-Za-z0-9._-]{8,100}$/.test(key))throw new HttpError(400,"IDEMPOTENCY_KEY_REQUIRED","A valid Idempotency-Key is required.");const body=await json(req),requestHash=sha256(JSON.stringify(body)),old=await repo.getIdempotency("public-inquiry",key);if(old){if(old.requestHash!==requestHash)throw new HttpError(409,"IDEMPOTENCY_CONFLICT","The idempotency key was used for another request.");return sendJson(res,old.status,old.body)}const p=validateInquiry(body);if(!p.ok)throw new HttpError(422,"VALIDATION_FAILED","Inquiry data is invalid.",p.errors);const row=await repo.addInquiry(p.value),payload={inquiry:{id:row.id,inquiryNo:row.inquiryNo,status:row.status,createdAt:row.createdAt}};await repo.saveIdempotency("public-inquiry",key,requestHash,201,payload);await audit(req,id,{action:"INQUIRY_CREATE",entityType:"inquiry",entityId:row.id,outcome:"success"});return sendJson(res,201,payload)}
  if(req.method==="GET"&&url.pathname==="/api/v1/students/me/summary"){const a=await auth(req);allow(a.user,"student:summary:read:own");return sendJson(res,200,{student:await repo.findStudent(a.user.studentRecordId)})}
  const sm=url.pathname.match(/^\/api\/v1\/students\/([^/]+)\/summary$/);if(req.method==="GET"&&sm){const a=await auth(req);allow(a.user,"student:summary:read:any");const s=await repo.findStudent(decodeURIComponent(sm[1]));if(!s)throw new HttpError(404,"STUDENT_NOT_FOUND","Student summary was not found.");return sendJson(res,200,{student:s})}
  throw new HttpError(404,"NOT_FOUND","API endpoint was not found.")}
 async function staticFile(req,res,url){if(url.pathname==="/apps/admin-web/navigation.js"){const data=await readFile(join(root,"packages/domain/src/admin-navigation.js"));res.writeHead(200,{"Content-Type":mime[".js"]});return res.end(data)}const route=url.pathname==="/"?"/apps/public-web/index.html":url.pathname==="/student"?"/apps/student-portal/index.html":(url.pathname==="/admin"||url.pathname.startsWith("/admin/"))?"/apps/admin-web/index.html":url.pathname,rel=normalize(route).replace(/^([/\\])+/,'');if(!rel.startsWith("apps/")&&!rel.startsWith("apps\\"))throw new HttpError(404,"NOT_FOUND","Page was not found.");const data=await readFile(join(root,rel)).catch(()=>null);if(!data)throw new HttpError(404,"NOT_FOUND","Page was not found.");res.writeHead(200,{"Content-Type":mime[extname(rel)]||"application/octet-stream","Cache-Control":"no-cache"});res.end(data)}
 return createServer(async(req,res)=>{const id=requestId(req);Object.entries(securityHeaders(config,id)).forEach(([k,v])=>res.setHeader(k,v));try{const url=new URL(req.url,config.origin);url.pathname.startsWith("/api/")?await api(req,res,url,id):await staticFile(req,res,url)}catch(e){const known=e instanceof HttpError;if(!known)console.error(JSON.stringify({level:"error",requestId:id,message:e.message}));sendJson(res,known?e.status:500,{error:{code:known?e.code:"INTERNAL_ERROR",message:known?e.message:"An unexpected error occurred.",...(known&&e.details?{details:e.details}:{}),requestId:id}})}})
}

