import {HttpError,sendJson} from './lib/http.js';
const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T00:00:00Z'));
const input=b=>{if(!b||typeof b!=='object'||Array.isArray(b))throw new HttpError(422,'VALIDATION_FAILED','Payment data is invalid.');const amountPaise=Math.round(Number(b.amount)*100),date=String(b.date||''),mode=String(b.mode||'').trim(),reference=String(b.reference||'').trim();if(!Number.isSafeInteger(amountPaise)||amountPaise<=0||!validDate(date)||!mode||mode.length>40||reference.length>120)throw new HttpError(422,'VALIDATION_FAILED','Enter a positive amount, valid date and payment mode.');return{amountPaise,date,mode,reference,...(b.version===undefined?{}:{version:b.version})};};
export async function financeRoute(req,res,url,id,{repo,auth,allow,csrf,requireSameOrigin,config,json,ipHash}){const m=url.pathname.match(/^\/api\/v1\/admin\/finance(?:\/students\/([^/]+))?(?:\/payments(?:\/([^/]+))?)?$/);if(!m)return false;const a=await auth(req);allow(a.user,'admin:dashboard:read');if(!repo.financeList)throw new HttpError(501,'INTEGRATION_PENDING','Financial repository integration is pending.');const studentId=m[1]?decodeURIComponent(m[1]):null,paymentId=m[2]?decodeURIComponent(m[2]):null;
 if(req.method==='GET'&&!studentId){const kind=url.searchParams.get('kind')||'fees',query=(url.searchParams.get('query')||'').slice(0,120),asOf=url.searchParams.get('asOf')||new Date().toISOString().slice(0,10);return sendJson(res,200,{items:await repo.financeList(kind,{query,asOf}),asOf});}
 if(req.method==='GET'&&studentId&&!paymentId){const row=await repo.financeStudent(studentId,url.searchParams.get('asOf'));if(!row)throw new HttpError(404,'STUDENT_NOT_FOUND','Student was not found.');return sendJson(res,200,{finance:row});}
 allow(a.user,'system:admin');requireSameOrigin(req,config);csrf(req,a.session);const event={actorUserId:a.user.id,actorRole:a.user.role,requestId:id,ipHash:ipHash(req),outcome:'success'};
 if(req.method==='POST'&&studentId&&!paymentId){const key=String(req.headers['idempotency-key']||'');if(!/^[A-Za-z0-9._-]{16,100}$/.test(key))throw new HttpError(422,'IDEMPOTENCY_KEY_REQUIRED','Supply a stable Idempotency-Key (16-100 characters) for payment retries.');const result=await repo.financeCreatePayment(studentId,input(await json(req)),event,`:${key}`);return sendJson(res,result.replayed?200:201,{payment:result.payment,replayed:Boolean(result.replayed)});}
 if(req.method==='PATCH'&&studentId&&paymentId){const v=input(await json(req));if(!Number.isSafeInteger(v.version)||v.version<1)throw new HttpError(422,'VALIDATION_FAILED','A valid payment version is required.');return sendJson(res,200,{payment:await repo.financeUpdatePayment(studentId,paymentId,v,event)});}
 if(req.method==='DELETE'&&studentId&&paymentId){const b=await json(req);if(!Number.isSafeInteger(b?.version)||b.version<1)throw new HttpError(422,'VALIDATION_FAILED','A valid payment version is required.');return sendJson(res,200,{payment:await repo.financeReversePayment(studentId,paymentId,b.version,event)});}
 throw new HttpError(405,'METHOD_NOT_ALLOWED','This financial action is not supported.');}
